### PR TITLE
Added Alert component

### PR DESCRIPTION
**Pull request by guastallaigor**
This address #27 .

**Added in Docs:**

**1. Alert component:**

image

**2. Show documentation button:**

image

----------------------
If I'm missing something, or you want something to be different please just let me know. Thank you.

### CODE REVIEW

**Comment by LeCoupa** [comment]
Thank you. I'll merge this in a few hours. :)

I will probably make some changes also.

**Comment by LeCoupa** [comment]
I made a few changes to your PR. Will merge tonight :)

**Comment by LeCoupa** [comment]
Among other things, here is what I did:

- Transition should be added by the developer himself. It should not be part of the component.
- I removed the title prop for the time being. I will add it later if I find a way to style it accordingly.
- I used flexbox to style and adjust the content.
- I added the "close" event so people can subscribe to it and close the banner by themselves (and other things if they need to).

https://www.vuedarkmode.com/#baseAlert

Thank you again for your work! :) If you disagree with some of my changes, feel free to tell me.

Also, can I add you as a contributor on the readme? (will add this part very soon)

**Comment by guastallaigor** [comment]
@LeCoupa Thank you. The alert docs looks a lot cleaner and better now. I don't disagree with anything.

You can add me in the contributor on the readme if you want :).

Just a side note, maybe add it in the readme base components also?

**Comment by LeCoupa** [comment]
Great! Yes I added it to the readme :)

**Comment by LeCoupa** [comment]
Just added you to the contributors on the readme. :-)

**Comment by guastallaigor** [comment]
> Just added you to the contributors on the readme. :-)

Thank you :)

**Comment by scoutrul** [comment]
Where is this future now??

**Comment by LeCoupa** [comment]
Hello @scoutrul, do you mean "this feature"? Or are you referring to something else?

**Pull request merged**
