### PR TITLE
refactor(package): prettier warnings removed

### PR DESCRIPTION
**Pull request by guastallaigor**
At this time on master there's prettier 13 warnings.

image

This PR is to remove then all.

I will later open an issue about how you could prevent that by adding a pre-push/commit hook that run the prettier lint and remove the warnings, and if there's an error it prevents the user to push the commit. But I will need to do some more research because I'm not entirely sure how to configurate this.

### CODE REVIEW

**Comment by LeCoupa** [comment]
How did you proceed to get these warnings? I am using Visual Studio Code with [this plugin](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) but I don't see these 13 warnings.

**Comment by guastallaigor** [comment]
This happened when I cloned the repository to do the #32 PR and opened the browser `devtools`. So my guess is they got fixed in another PR. Sorry about that.

**Comment by LeCoupa** [comment]
Yes, I made some changes in another PR that included this fix. Thank you for the PR though and Happy Christmas! 🎅🏻

**Comment by guastallaigor** [comment]
Thank you! Happy Christmas to you too! :santa:

**Pull request closed without merging**
