### PR TITLE
copy scss colour variables into build

### PR DESCRIPTION
**Pull request by ZainW**
Hello

creating this PR so that I can use the SCSS colour variables in my project as is. While the variables listed on the docs are SCSS variables they are unavailable when built

this pr just copies it over into the dist folder on build. Let me know if you want it in another folder or something but this would be super nice to have when creating projects with Vue Dark Mode

### CODE REVIEW

**Comment by ZainW** [comment]
@LeCoupa pretty please can you look at this?

**Comment by LeCoupa** [comment]
Yes, I'll check this in a few hours :)

**Comment by ZainW** [comment]
🙏 appreciate it

**Comment by LeCoupa** [comment]
Sorry I forgot about this. I'm back in my computer in an hour. I will merge this. ,,🌱

**Comment by LeCoupa** [comment]
Thank you! Sorry for the delay. Are you using Vue Dark Mode in a side project? :)

**Pull request merged**
